version: 2
models:
  - name: dim_boat
    description: dimension boat
    columns:
      - name: boat_id
        data_tests:
          - not_null
          - unique
  - name: dim_community
    description: dimension community
    columns:
      - name: community_id
        data_tests:
          - not_null
          - unique
  - name: dim_date
    description: dimension date
    columns:
      - name: date_id
        data_tests:
          - not_null
          - unique
  - name: dim_trip_purpose
    description: dimension community
    columns:
      - name: trip_purpose_id
        data_tests:
          - not_null
          - unique
  - name: stg_telemetry
    description: stg from raw telemetry
    columns:
      - name: boat
        data_tests:
          - not_null
      - name: telemetry_datetime
        data_tests:
          - not_null